version: '3'

services:
  peopleservice:
    container_name: peopleservice_development
    image: peopleservice
    ports:
      - "5000:80"
    depends_on:
      - db
    build:
      context: ./PeopleService
      dockerfile: Dockerfile
  
  db:
    image: microsoft/mssql-server-linux
    container_name: peopleservice_dev_db
    environment:
      SA_PASSWORD: password123(!)
      ACCEPT_EULA: "Y"

    