version: '3'

services:
  peopleservice:
    container_name: PeopleService
    environment:
      - DOCKER_INSTANCE=TRUE
    image: thornpar/peopleservice:latest
    ports: 
      - "8000:80"
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    container_name: db
    volumes:
      - db-data:/var/opt/mssql/
    ports:
        - "1433:1433"
    environment:
      SA_PASSWORD: password123(!)
      ACCEPT_EULA: "Y"
  cache:
    image: redis

volumes:
  db-data: